deployment:
  tasks:
    - echo "Starting deployment tasks..."
    - cd backend
    - npm install
    - echo "Dependencies installed."

name: hotelmanagement
app_root: backend
app_port: 3000
app_environment: production
app_startup_file: clean-server.js